name: PowerGems
version: '${project.version}'
main: me.iseal.powergems.Main
api-version: '1.19'
author: ISeal
commands:
  givegem:
    description: Command to give yourself a gem
    usage: /givegem <gem>
    permission: powergems.givegem
  giveallgem:
    description: Command to give everyone a gem
    usage: /giveallgem <gem>
    permission: powergems.giveallgem
  checkupdates:
    description: Command to check for updates
    usage: /checkupdates
    permission: powergems.checkupdates
  reloadconfig:
    description: Command to reload the config files
    usage: /reloadconfig
    permission: powergems.reloadconfig
permissions:
    powergems.givegem:
        description: Permission to use /givegem
        default: op
    powergems.giveallgem:
        description: Permission to use /giveallgem
        default: op
    powergems.checkupdates:
        description: Permission to use /checkupdates
        default: true
    powergems.reloadconfig:
        description: Permission to use /reloadconfig
        default: op
    powergems.*:
        description: Permission to use all PowerGems commands
        default: op
        children:
            powergems.givegem: true
            powergems.giveallgem: true
            powergems.checkupdates: true
            powergems.reloadconfig: true
